name: React Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Change directory
      run: cd frontend  # Change 'frontend' to your project's directory if different

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
